var cityFinder = {
    Afghanistan: "Kabul",
    Albania: "Tirana",
    Algeria: "Algiers",
    Andorra: "Andorra la Vella",
    Angola: "Luanda",
    Antigua_and_Barbuda: "Saint John's",
    Argentina: "Buenos Aires",
    Armenia: "Yerevan",
    Australia: "Canberra",
    Austria: "Vienna",
    Azerbaijan: "Baku",
    Bahamas: "Nassau",
    Bahrain: "Manama",
    Bangladesh: "Dhaka",
    Barbados: "Bridgetown",
    Belarus: "Minsk",
    Belgium: "Brussels",
    Belize: "Belmopan",
    Benin: "Porto-Novo",
    Bhutan: "Thimpu",
    Bolivia: "Sucre (de jure) or La Paz (government location)",
    Bosnia_and_Herzegovina: "Sarajevo",
    Botswana: "Gaborone",
    Brazil: "Brasilia",
    Brunei: "Bandar Seri Begawan",
    Bulgaria: "Sofia",
    Burkina_Faso: "Ouagadougou",
    Burundi: "Gitega",
    Cape_Verde: "Praia",
    Cambodia: "Phnom Penh",
    Cameroon: "Yaounde",
    Canada: "Ottawa",
    Central_African_Republic: "Bangui",
    Chad: "N'Djamena",
    Chile: "Santiago",
    China: "Beijing",
    Colombia: "Bogotá",
    Comoros: "Moroni",
    Costa_Rica: "San Jose",
    Croatia: "Zagreb",
    Cuba: "Havana",
    Cyprus: "Nicosia",
    Czech_Republic: "Prague",
    Democratic_Republic_of_the_Congo: "Kinshasa",
    Denmark: "Copenhagen",
    Djibouti: "Djibouti City",
    Dominica: "Roseau",
    Dominican_Republic: "Santo Domingo",
    Ecuador: "Quito",
    Egypt: "Cairo",
    El_Salvador: "San Salvador",
    England: "London",
    Equatorial_Guinea: "Malabo (de jure), Oyala (government location)",
    Eritrea: "Asmara",
    Estonia: "Tallinn",
    Eswatini: "Mbabane",
    Ethiopia: "Addis Ababa",
    Fiji: "Suva",
    Finland: "Helsinki",
    France: "Paris",
    Georgia: "Tbilisi",
    Germany: "Berlin",
    Greece: "Athens",
    Guyana: "Georgetown",
    Hungary: "Budapest",
    Iceland: "Reykjavik",
    Ireland: "Dublin",
    Italy: "Rome",
    Ivory_Coast: "Yamoussoukro",
    Jamaica: "Kingston",
    Kazakhstan: "Nur-Sultan",
    Kosovo: "Pristina",
    Latvia: "Riga",
    Liechtenstein: "Vaduz",
    Lithuania: "Vilnius",
    Malta: "Vilnius",
    Moldova: "Chisinau",
    Montenegro: "Podgorica",
    Netherlands: "Amsterdam",
    North_Macedonia: "Skopje",
    Norway: "Oslo",
    Poland: "Warsaw",
    Portugal: "Lisbon",
    Quebec: "Quebec City",
    Poland: "Warsaw",
    Portugal: "London",
    Republic_of_the_Congo: "Brazzaville",
    Romania: "Bucharest",
    Russia: "Moscow",
    Serbia: "Belgrade",
    Slovakia: "Bratislava",
    Slovenia: "Ljubljana",
    Spain: "Madrid",
    Sweden: "Stockholm",
    Switzerland: "Bern",
    Turkey: "Ankara",
    Ukraine: "Kyev",
    United_Kingdom: "London",
};

console.log(cityFinder.Jamaica);