var cityFinder = {
    Afghanistan: "Kabul",
    Albania: "Tirana",
    Andorra: "Andorra la Vella",
    Armenia: "Yerevan",
    Austria: "Vienna",
    Azerbaijan: "Baku",
    Belarus: "Minsk",
    Belgium: "Brussels",
    Bosnia_and_Herzegovina: "Sarajevo",
    Bulgaria: "Sofia",
    Canada: "Ottawa",
    Croatia: "Zagreb",
    Cyprus: "Nicosia",
    Czech_Republic: "Prague",
    Denmark: "Copenhagen",
    England: "London",
    Estonia: "Tallinn",
    Finland: "Helsinki",
    France: "Paris",
    Georgia: "Tbilisi",
    Germany: "Berlin",
    Greece: "Athens",
    Guyana: "Georgetown",
    Hungary: "Budapest",
    Iceland: "Reykjavik",
    Ireland: "Dublin",
    Italy: "Rome",
    Jamaica: "Kingston",
    Kazakhstan: "Nur-Sultan",
    Kosovo: "Pristina",
    Latvia: "Riga",
    Liechtenstein: "Vaduz",
    Lithuania: "Vilnius",
    Malta: "Vilnius",
    Moldova: "Chisinau",
    Montenegro: "Podgorica",
    Netherlands: "Amsterdam",
    North_Macedonia: "Skopje",
    Norway: "Oslo",
    Poland: "Warsaw",
    Portugal: "Lisbon",
    Quebec: "Quebec City",
    Poland: "Warsaw",
    Portugal: "London",
    Romania: "Bucharest",
    Russia: "Moscow",
    Serbia: "Belgrade",
    Slovakia: "Bratislava",
    Slovenia: "Ljubljana",
    Spain: "Madrid",
    Sweden: "Stockholm",
    Switzerland: "Bern",
    Turkey: "Ankara",
    Ukraine: "Kyev",
    United_Kingdom: "London",
};

console.log(cityFinder.Jamaica);